### ISSUE TITLE
testing privlages

### ISSUE THREAD

**Issue by bstone** [adelphimathcs/testrepo#1]
@MattMatero, we have changed the privileges for the teams. I believe the @adelphimathcs/students  can see this repo, but cannot push to it. Someone correct me if I am wrong. However, I think that @adelphimathcs/alumni can view/clone/push. That is how the teams work. If you want @MattMatero, I can make you team maintainer for the Alumni team. Let me know.

Edit: I have been giving team members Admin privileges to new repos of any team they are in. The default privilege is just read permission.

**Comment by MattMatero** [comment]
What would be my tasks as a team maintainer? I'd be open to doing it since I'm fairly active in the org anyway.

**Comment by MichaelVessia** [comment]
@b-stone I can confirm that I cannot push to this repo.  I can however fork it and create pull requests.

**Comment by bstone** [comment]
@MichaelVessia, Thanks. That is how I wanted it to behave. 

@MattMatero, no tasks in particular. It just means you have more power to edit/manage. You can also shape the team goals if you want, but don't have to.  If at some point you feel like you don't want to be active anymore, then don't be active; you would still keep the maintainer status.

**Comment by MattMatero** [comment]
@b-stone Okay sure sounds good to me.

**Comment by bstone** [comment]
Great. Thanks.
